//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Base schema for adressable entities */
public class Addressable: APIModel {

    /** Hyperlink reference */
    public var href: URL?

    /** unique identifier */
    public var id: String?

    public init(href: URL? = nil, id: String? = nil) {
        self.href = href
        self.id = id
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        href = try container.decodeIfPresent("href")
        id = try container.decodeIfPresent("id")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(href, forKey: "href")
        try container.encodeIfPresent(id, forKey: "id")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Addressable else { return false }
      guard self.href == object.href else { return false }
      guard self.id == object.id else { return false }
      return true
    }

    public static func == (lhs: Addressable, rhs: Addressable) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
