//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A type of ProductOffering that belongs to a grouping of ProductOfferings made available to the market. It inherits of all attributes of ProductOffering. */
public class BundledProductOffering: APIModel {

    /** When sub-classing, this defines the super-class */
    public var alphabaseType: String?

    /** A URI to a JSON-Schema file that defines additional attributes and relationships */
    public var alphaschemaLocation: URL?

    /** When sub-classing, this defines the sub-class Extensible name */
    public var alphatype: String?

    public var bundledProductOfferingOption: BundledProductOfferingOption?

    /** Unique reference of the BundledProductOffering */
    public var href: String?

    /** Unique identifier of the BundledProductOffering */
    public var id: String?

    /** Used to indicate the current lifecycle status */
    public var lifecycleStatus: String?

    /** Name of the BundledProductOffering */
    public var name: String?

    public init(alphabaseType: String? = nil, alphaschemaLocation: URL? = nil, alphatype: String? = nil, bundledProductOfferingOption: BundledProductOfferingOption? = nil, href: String? = nil, id: String? = nil, lifecycleStatus: String? = nil, name: String? = nil) {
        self.alphabaseType = alphabaseType
        self.alphaschemaLocation = alphaschemaLocation
        self.alphatype = alphatype
        self.bundledProductOfferingOption = bundledProductOfferingOption
        self.href = href
        self.id = id
        self.lifecycleStatus = lifecycleStatus
        self.name = name
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        alphabaseType = try container.decodeIfPresent("@baseType")
        alphaschemaLocation = try container.decodeIfPresent("@schemaLocation")
        alphatype = try container.decodeIfPresent("@type")
        bundledProductOfferingOption = try container.decodeIfPresent("bundledProductOfferingOption")
        href = try container.decodeIfPresent("href")
        id = try container.decodeIfPresent("id")
        lifecycleStatus = try container.decodeIfPresent("lifecycleStatus")
        name = try container.decodeIfPresent("name")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(alphabaseType, forKey: "@baseType")
        try container.encodeIfPresent(alphaschemaLocation, forKey: "@schemaLocation")
        try container.encodeIfPresent(alphatype, forKey: "@type")
        try container.encodeIfPresent(bundledProductOfferingOption, forKey: "bundledProductOfferingOption")
        try container.encodeIfPresent(href, forKey: "href")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(lifecycleStatus, forKey: "lifecycleStatus")
        try container.encodeIfPresent(name, forKey: "name")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? BundledProductOffering else { return false }
      guard self.alphabaseType == object.alphabaseType else { return false }
      guard self.alphaschemaLocation == object.alphaschemaLocation else { return false }
      guard self.alphatype == object.alphatype else { return false }
      guard self.bundledProductOfferingOption == object.bundledProductOfferingOption else { return false }
      guard self.href == object.href else { return false }
      guard self.id == object.id else { return false }
      guard self.lifecycleStatus == object.lifecycleStatus else { return false }
      guard self.name == object.name else { return false }
      return true
    }

    public static func == (lhs: BundledProductOffering, rhs: BundledProductOffering) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
