//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Sets the communication endpoint address the service instance must use to deliver notification information */
public class EventSubscription: APIModel {

    /** The callback being registered. */
    public var callback: String

    /** Id of the listener */
    public var id: String

    /** additional data to be passed */
    public var query: String?

    public init(callback: String, id: String, query: String? = nil) {
        self.callback = callback
        self.id = id
        self.query = query
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        callback = try container.decode("callback")
        id = try container.decode("id")
        query = try container.decodeIfPresent("query")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(callback, forKey: "callback")
        try container.encode(id, forKey: "id")
        try container.encodeIfPresent(query, forKey: "query")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EventSubscription else { return false }
      guard self.callback == object.callback else { return false }
      guard self.id == object.id else { return false }
      guard self.query == object.query else { return false }
      return true
    }

    public static func == (lhs: EventSubscription, rhs: EventSubscription) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
