//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Valid values for the state of a batch job (e.g. catalog import) */
/** Valid values for the state of a batch job (e.g. catalog import) */
public enum JobStateType: String, Codable, Equatable, CaseIterable {
    case notStarted = "Not Started"
    case running = "Running"
    case succeeded = "Succeeded"
    case failed = "Failed"
}
