//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The event data structure */
public class ProductSpecificationDeleteEventPayload: APIModel {

    public var productSpecification: ProductSpecification?

    public init(productSpecification: ProductSpecification? = nil) {
        self.productSpecification = productSpecification
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        productSpecification = try container.decodeIfPresent("productSpecification")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(productSpecification, forKey: "productSpecification")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ProductSpecificationDeleteEventPayload else { return false }
      guard self.productSpecification == object.productSpecification else { return false }
      return true
    }

    public static func == (lhs: ProductSpecificationDeleteEventPayload, rhs: ProductSpecificationDeleteEventPayload) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
