//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** An aggregation, migration, substitution, dependency or exclusivity relationship between/among productSpecificationCharacteristics. */
public class ProductSpecificationCharacteristicRelationship: APIModel {

    /** When sub-classing, this defines the super-class */
    public var alphabaseType: String?

    /** A URI to a JSON-Schema file that defines additional attributes and relationships */
    public var alphaschemaLocation: URL?

    /** When sub-classing, this defines the sub-class Extensible name */
    public var alphatype: String?

    /** The order in which a CharacteristicSpecification appears within another CharacteristicSpecification that defines a grouping of CharacteristicSpecifications.
For example, a grouping may represent the name of an individual. The given name is first, the middle name is second, and the last name is third. */
    public var charSpecSeq: Int?

    /** Hyperlink reference to the target product specification */
    public var href: String?

    /** the identifier of the associated product specification */
    public var id: String?

    /** Name of the target product specification characteristic */
    public var name: String?

    /** Type of relationship such as aggregation, migration, substitution, dependency, exclusivity */
    public var relationshipType: String?

    public var validFor: TimePeriod?

    public init(alphabaseType: String? = nil, alphaschemaLocation: URL? = nil, alphatype: String? = nil, charSpecSeq: Int? = nil, href: String? = nil, id: String? = nil, name: String? = nil, relationshipType: String? = nil, validFor: TimePeriod? = nil) {
        self.alphabaseType = alphabaseType
        self.alphaschemaLocation = alphaschemaLocation
        self.alphatype = alphatype
        self.charSpecSeq = charSpecSeq
        self.href = href
        self.id = id
        self.name = name
        self.relationshipType = relationshipType
        self.validFor = validFor
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        alphabaseType = try container.decodeIfPresent("@baseType")
        alphaschemaLocation = try container.decodeIfPresent("@schemaLocation")
        alphatype = try container.decodeIfPresent("@type")
        charSpecSeq = try container.decodeIfPresent("charSpecSeq")
        href = try container.decodeIfPresent("href")
        id = try container.decodeIfPresent("id")
        name = try container.decodeIfPresent("name")
        relationshipType = try container.decodeIfPresent("relationshipType")
        validFor = try container.decodeIfPresent("validFor")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(alphabaseType, forKey: "@baseType")
        try container.encodeIfPresent(alphaschemaLocation, forKey: "@schemaLocation")
        try container.encodeIfPresent(alphatype, forKey: "@type")
        try container.encodeIfPresent(charSpecSeq, forKey: "charSpecSeq")
        try container.encodeIfPresent(href, forKey: "href")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(relationshipType, forKey: "relationshipType")
        try container.encodeIfPresent(validFor, forKey: "validFor")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ProductSpecificationCharacteristicRelationship else { return false }
      guard self.alphabaseType == object.alphabaseType else { return false }
      guard self.alphaschemaLocation == object.alphaschemaLocation else { return false }
      guard self.alphatype == object.alphatype else { return false }
      guard self.charSpecSeq == object.charSpecSeq else { return false }
      guard self.href == object.href else { return false }
      guard self.id == object.id else { return false }
      guard self.name == object.name else { return false }
      guard self.relationshipType == object.relationshipType else { return false }
      guard self.validFor == object.validFor else { return false }
      return true
    }

    public static func == (lhs: ProductSpecificationCharacteristicRelationship, rhs: ProductSpecificationCharacteristicRelationship) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
