//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The reference object to the schema and type of target product which is described by product specification */
public class TargetProductSchema: APIModel {

    /** This field provides a link to the schema describing the target product */
    public var alphaschemaLocation: URL

    /** Class type of the target product */
    public var alphatype: String

    public init(alphaschemaLocation: URL, alphatype: String) {
        self.alphaschemaLocation = alphaschemaLocation
        self.alphatype = alphatype
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        alphaschemaLocation = try container.decode("@schemaLocation")
        alphatype = try container.decode("@type")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(alphaschemaLocation, forKey: "@schemaLocation")
        try container.encode(alphatype, forKey: "@type")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? TargetProductSchema else { return false }
      guard self.alphaschemaLocation == object.alphaschemaLocation else { return false }
      guard self.alphatype == object.alphatype else { return false }
      return true
    }

    public static func == (lhs: TargetProductSchema, rhs: TargetProductSchema) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
