//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A tax item is created for each tax rate and tax type used in the bill. */
public class TaxItem: APIModel {

    /** When sub-classing, this defines the super-class */
    public var alphabaseType: String?

    /** A URI to a JSON-Schema file that defines additional attributes and relationships */
    public var alphaschemaLocation: URL?

    /** When sub-classing, this defines the sub-class Extensible name */
    public var alphatype: String?

    /** Hyperlink reference */
    public var href: URL?

    /** unique identifier */
    public var id: String?

    public var taxAmount: Money?

    /** Tax category */
    public var taxCategory: String?

    /** Applied rate of the tax */
    public var taxRate: Float?

    public init(alphabaseType: String? = nil, alphaschemaLocation: URL? = nil, alphatype: String? = nil, href: URL? = nil, id: String? = nil, taxAmount: Money? = nil, taxCategory: String? = nil, taxRate: Float? = nil) {
        self.alphabaseType = alphabaseType
        self.alphaschemaLocation = alphaschemaLocation
        self.alphatype = alphatype
        self.href = href
        self.id = id
        self.taxAmount = taxAmount
        self.taxCategory = taxCategory
        self.taxRate = taxRate
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        alphabaseType = try container.decodeIfPresent("@baseType")
        alphaschemaLocation = try container.decodeIfPresent("@schemaLocation")
        alphatype = try container.decodeIfPresent("@type")
        href = try container.decodeIfPresent("href")
        id = try container.decodeIfPresent("id")
        taxAmount = try container.decodeIfPresent("taxAmount")
        taxCategory = try container.decodeIfPresent("taxCategory")
        taxRate = try container.decodeIfPresent("taxRate")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(alphabaseType, forKey: "@baseType")
        try container.encodeIfPresent(alphaschemaLocation, forKey: "@schemaLocation")
        try container.encodeIfPresent(alphatype, forKey: "@type")
        try container.encodeIfPresent(href, forKey: "href")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(taxAmount, forKey: "taxAmount")
        try container.encodeIfPresent(taxCategory, forKey: "taxCategory")
        try container.encodeIfPresent(taxRate, forKey: "taxRate")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? TaxItem else { return false }
      guard self.alphabaseType == object.alphabaseType else { return false }
      guard self.alphaschemaLocation == object.alphaschemaLocation else { return false }
      guard self.alphatype == object.alphatype else { return false }
      guard self.href == object.href else { return false }
      guard self.id == object.id else { return false }
      guard self.taxAmount == object.taxAmount else { return false }
      guard self.taxCategory == object.taxCategory else { return false }
      guard self.taxRate == object.taxRate else { return false }
      return true
    }

    public static func == (lhs: TaxItem, rhs: TaxItem) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
