//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** ## TMF API Reference: TMF620 - Product Catalog Management
### Release : 20.5 - March 2021
Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products. 
### Operations
Product Catalog API performs the following operations on the resources :
- Retrieve an entity or a collection of entities depending on filter criteria
- Partial update of an entity (including updating rules)
- Create an entity (including default values and creation rules)
- Delete an entity
- Manage notification of events */
public struct TMF620 {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = false

    /// Used to encode Dates when uses as string params
    public static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                                                            locale: Locale(identifier: "en_US_POSIX"),
                                                            calendar: Calendar(identifier: .gregorian))

    public static let version = "4.1.0"

    public enum Catalog {}
    public enum Category {}
    public enum EventsSubscription {}
    public enum ExportJob {}
    public enum ImportJob {}
    public enum NotificationListeners {}
    public enum ProductOffering {}
    public enum ProductOfferingPrice {}
    public enum ProductSpecification {}

    public enum Server {

        public static let main = "https://serverRoot/tmf-api/productCatalogManagement/v4/"
    }
}
